const text = {
    fr: {
        msgs: {
            save: 'Enregistrer',
            preview: 'Aperçu',
            presentationText: 'Text',

        }
    }
}

export {
    text
}

export const translations = {
    fr: {
        home: 'Accueil',
        activities: 'Activités & Réservations',
        'organisateur.space': 'Espace Organisateur',
        'organistaeur.manager': 'Manager',
        'organisateur.create': 'Créer un Événement',
        'organisateur.map': 'Gérer la Carte',
        'prestataire.space': 'Espace Prestataire',
        'prestataire.services': 'Mes Services',
        'prestataire.bookings': 'Mes Réservations',
        'myAccount': 'Mon Compte',
        'notifications': 'Notifications',
        'about': 'À Propos',
        'login': 'Connexion',
        'logout': 'Déconnexion',
        'profile': 'Mon Profil',
        'settings': 'Paramètres',
        'contact': 'Contactez nous',
        'login.with.google': 'Se connecter avec Google',
        'login.with.social': 'Ou se connecter via',
        'register.with.google': 'S\'inscrire avec Google',
        'register.with.social': 'Ou s\'inscrire via',
        'cancel': 'Annuler',
        'save': 'Enregistrer',
        'delete': 'Supprimer',
        'edit': 'Modifier',
        'back': 'Retour',
        'home.return': 'Retour à l\'accueil',

        'account.title': 'Mon Compte',
        'account.notConnected': 'Vous devez être connecté pour accéder à cette page.',
        'account.tickets': 'Mes Billets',
        'account.activities': 'Mes Activités',
        'account.security': 'Sécurité',
        'account.fullName': 'Nom Complet',
        'account.emailReadOnly': 'Email (non modifiable)',
        'account.phone': 'Téléphone',
        'account.description': 'Bio / Description',
        'account.picture': 'URL de la photo de profil',
        'account.saveChanges': 'Enregistrer les modifications',
        'account.myReviews': 'Mes Avis',
        'account.noReviews': 'Vous n\'avez pas encore laissé d\'avis.',
        'account.uid': 'Identifiant unique:',

        'review.edit': 'Modifier mon avis',
        'review.rating': 'Note :',
        'review.comment': 'Commentaire :',

        'ticket.holder': 'Détenteur',
        'ticket.date': 'Acheté le',
        'ticket.empty': 'Vous n\'avez aucun billet pour le moment.',
        'ticket.goto': 'Aller à la billetterie',

        'reservation.my': 'Mes Réservations',
        'reservation.empty': 'Aucune réservation pour le moment.',
        'reservation.view': 'Voir les activités',

        'admin.globalTracking': 'Administration - Suivi global',
        'admin.client': 'Client',
        'admin.activity': 'Activité',
        'admin.date': 'Date',
        'admin.action': 'Action',
        'admin.title': 'Admin Necronomi\'Con',
        'admin.subtitle': 'Panneau de contrôle des prestataires, de la carte et des activités.',
        'admin.providers': 'Prestataires',
        'admin.map': 'Carte',
        'admin.accounts': 'Comptes',

        'security.instructions': 'Pour changer votre mot de passe, veuillez remplir les champs ci-dessous.',
        'security.currentPass': 'Mot de passe actuel',
        'security.newPass': 'Nouveau mot de passe',
        'security.confirmPass': 'Confirmer le mot de passe',
        'security.updatePass': 'Mettre à jour le mot de passe',

        'prestataire.error': 'Vous n\'êtes pas reconnu comme un prestataire ou n\'êtes pas connecté.',
        'prestataire.space.title': 'Espace Prestataire : ',
        'prestataire.reviews': 'Avis Reçus',
        'prestataire.info': 'Informations Générales',
        'prestataire.name': 'Nom de l\'enseigne',
        'prestataire.email': 'Email de contact',
        'prestataire.phone': 'Téléphone',
        'prestataire.category': 'Catégorie',
        'prestataire.description': 'Description',
        'prestataire.saveProfile': 'Sauvegarder le profil',
        'prestataire.servicesList': 'Liste de mes prestations',
        'prestataire.newService': 'Nouvelle Prestation',
        'prestataire.colName': 'Nom',
        'prestataire.colZone': 'Zone',
        'prestataire.colCategory': 'Catégorie',
        'prestataire.reviewsTitle': 'Avis sur mes prestations',
        'prestataire.noReviews': 'Aucun avis reçu pour le moment.',
        'prestataire.editService': 'Modifier Prestation',
        'prestataire.zoneLabel': 'Zone / Emplacement',
        'prestataire.detailLabel': 'Description détaillée',
        'prestataire.status': 'Statut du stand :',
        'prestataire.validated': 'Validé',
        'prestataire.location': 'Emplacement :',
        'prestataire.manage': 'Gérer mes prestations',
        'prestataire.stand': 'Mon Stand',

        'globalSearch': 'Recherche globale...',
        'noResults': 'Aucun résultat trouvé.',
        'filterByName': 'Filtrer par nom',
        'chooseCategory': 'Choisir une catégorie',
        'independent': 'Indépendant',
        'linkedProvider': 'Prestataire lié',

        'admin.providerManager.title': 'Gestion des prestataires',
        'admin.providerManager.waitlist': 'Liste d\'attente',
        'admin.providerManager.list': 'Liste des prestataires',
        'admin.providerManager.new': 'Nouveau prestataire',
        'admin.providerManager.edit': 'Modifier un prestataire',
        'admin.providerManager.confirmDelete': 'Confirmer la suppression',
        'admin.providerManager.deletePrompt': 'Voulez-vous vraiment supprimer le prestataire',

        'admin.accountManager.title': 'Gestion des comptes',
        'admin.accountManager.colName': 'Nom',
        'admin.accountManager.colEmail': 'Email',
        'admin.accountManager.colRole': 'Rôle principal',
        'admin.accountManager.colActions': 'Actions',
        'admin.accountManager.editTitle': 'Modifier le compte : ',
        'admin.accountManager.roleLabel': 'Rôle principal',
        'admin.accountManager.rolePlaceholder': 'Sélectionner un rôle',
        'admin.accountManager.confirmDelete': 'Confirmer la suppression',
        'admin.accountManager.deletePrompt': 'Voulez-vous vraiment supprimer le compte',
        'admin.accountManager.deleteWarning': 'Attention : Ce compte étant un prestataire, ses prestations et son profil public seront également supprimés.',

        'admin.waitlist.title': 'File d\'attente Prestataires',
        'admin.waitlist.empty': 'Aucune demande en attente.',
        'admin.waitlist.colDate': 'Date de demande',
        'admin.waitlist.colServices': 'Services demandés',
        'admin.waitlist.accept': 'Accepter',
        'admin.waitlist.reject': 'Refuser',

        'category.artisan': 'Artisan',
        'category.atelier': 'Atelier',
        'category.jeu_video': 'Jeu vidéo',
        'category.jeu_plateau': 'Jeu de Plateau',
        'category.boutique': 'Boutique',
        'category.restauration': 'Restauration',
        'service.boissons_snacks': 'Boissons et snacks',
        'service.restauration_chaude': 'Restauration chaude',
        'service.vente_produits_derives': 'Vente produits dérivés',
        'service.vente_repliques_armes': 'Vente répliques armes',
        'service.animation_arcade': 'Animation arcade',
        'service.demo_vr': 'Démonstration VR',
        'service.reparation_costumes': 'Réparation costumes',
    },
    en: {
        home: 'Home',
        activities: 'Activities & Booking',
        'organisateur.space': 'Organizer Space',
        'organistaeur.manager': 'Manager',
        'organisateur.create': 'Create Event',
        'organisateur.map': 'Manage Map',
        'prestataire.space': 'Provider Space',
        'prestataire.services': 'My Services',
        'prestataire.bookings': 'My Bookings',
        'myAccount': 'My Account',
        'notifications': 'Notifications',
        'about': 'About',
        'login': 'Login',
        'logout': 'Logout',
        'profile': 'My Profile',
        'settings': 'Settings',
        'contact': 'Contact Us',
        'login.with.google': 'Login with Google',
        'login.with.social': 'Or login via',
        'register.with.google': 'Register with Google',
        'register.with.social': 'Or register via',
        'cancel': 'Cancel',
        'save': 'Save',
        'delete': 'Delete',
        'edit': 'Edit',
        'back': 'Back',
        'home.return': 'Return to Home',

        'account.title': 'My Account',
        'account.notConnected': 'You must be logged in to access this page.',
        'account.tickets': 'My Tickets',
        'account.activities': 'My Activities',
        'account.security': 'Security',
        'account.fullName': 'Full Name',
        'account.emailReadOnly': 'Email (read-only)',
        'account.phone': 'Phone',
        'account.description': 'Bio / Description',
        'account.picture': 'Profile Picture URL',
        'account.saveChanges': 'Save Changes',
        'account.myReviews': 'My Reviews',
        'account.noReviews': 'You haven\'t left any reviews yet.',
        'account.uid': 'Unique ID:',

        'review.edit': 'Edit my review',
        'review.rating': 'Rating:',
        'review.comment': 'Comment:',

        'ticket.holder': 'Holder',
        'ticket.date': 'Purchased on',
        'ticket.empty': 'You have no tickets at the moment.',
        'ticket.goto': 'Go to Ticketing',

        'reservation.my': 'My Bookings',
        'reservation.empty': 'No bookings at the moment.',
        'reservation.view': 'View Activities',

        'admin.globalTracking': 'Administration - Global Tracking',
        'admin.client': 'Client',
        'admin.activity': 'Activity',
        'admin.date': 'Date',
        'admin.action': 'Action',
        'admin.title': 'Necronomi\'Con Admin',
        'admin.subtitle': 'Provider, map and activity control panel.',
        'admin.providers': 'Providers',
        'admin.map': 'Map',
        'admin.accounts': 'Accounts',

        'security.instructions': 'To change your password, please fill in the fields below.',
        'security.currentPass': 'Current Password',
        'security.newPass': 'New Password',
        'security.confirmPass': 'Confirm Password',
        'security.updatePass': 'Update Password',

        'prestataire.error': 'You are not recognized as a provider or are not logged in.',
        'prestataire.space.title': 'Provider Space: ',
        'prestataire.reviews': 'Reviews Received',
        'prestataire.info': 'General Information',
        'prestataire.name': 'Brand Name',
        'prestataire.email': 'Contact Email',
        'prestataire.phone': 'Phone',
        'prestataire.category': 'Category',
        'prestataire.description': 'Description',
        'prestataire.saveProfile': 'Save Profile',
        'prestataire.servicesList': 'My Services List',
        'prestataire.newService': 'New Service',
        'prestataire.colName': 'Name',
        'prestataire.colZone': 'Zone',
        'prestataire.colCategory': 'Category',
        'prestataire.reviewsTitle': 'Reviews on my services',
        'prestataire.noReviews': 'No reviews received yet.',
        'prestataire.editService': 'Edit Service',
        'prestataire.zoneLabel': 'Zone / Location',
        'prestataire.detailLabel': 'Detailed Description',
        'prestataire.status': 'Booth Status:',
        'prestataire.validated': 'Validated',
        'prestataire.location': 'Location:',
        'prestataire.manage': 'Manage my services',
        'prestataire.stand': 'My Stand',

        'globalSearch': 'Global search...',
        'noResults': 'No results found.',
        'filterByName': 'Filter by name',
        'chooseCategory': 'Choose a category',
        'independent': 'Independent',
        'linkedProvider': 'Linked provider',

        'admin.providerManager.title': 'Provider Management',
        'admin.providerManager.waitlist': 'Waitlist',
        'admin.providerManager.list': 'Provider List',
        'admin.providerManager.new': 'New Provider',
        'admin.providerManager.edit': 'Edit Provider',
        'admin.providerManager.confirmDelete': 'Confirm Deletion',
        'admin.providerManager.deletePrompt': 'Do you really want to delete provider',

        'admin.accountManager.title': 'Account Management',
        'admin.accountManager.colName': 'Name',
        'admin.accountManager.colEmail': 'Email',
        'admin.accountManager.colRole': 'Main Role',
        'admin.accountManager.colActions': 'Actions',
        'admin.accountManager.editTitle': 'Edit Account: ',
        'admin.accountManager.roleLabel': 'Main Role',
        'admin.accountManager.rolePlaceholder': 'Select a role',
        'admin.accountManager.confirmDelete': 'Confirm Deletion',
        'admin.accountManager.deletePrompt': 'Do you really want to delete account',
        'admin.accountManager.deleteWarning': 'Warning: As this is a provider account, its services and public profile will also be deleted.',

        'admin.waitlist.title': 'Provider Waitlist',
        'admin.waitlist.empty': 'No pending requests.',
        'admin.waitlist.colDate': 'Request Date',
        'admin.waitlist.colServices': 'Requested services',
        'admin.waitlist.accept': 'Accept',
        'admin.waitlist.reject': 'Reject',

        'category.artisan': 'Craftsman',
        'category.atelier': 'Workshop',
        'category.jeu_video': 'Video Game',
        'category.jeu_plateau': 'Board Game',
        'category.boutique': 'Shop',
        'category.restauration': 'Catering',
        'service.boissons_snacks': 'Drinks and snacks',
        'service.restauration_chaude': 'Hot food',
        'service.vente_produits_derives': 'Merchandise sales',
        'service.vente_repliques_armes': 'Weapon replica sales',
        'service.animation_arcade': 'Arcade animation',
        'service.demo_vr': 'VR demo',
        'service.reparation_costumes': 'Costume repair',
    }
}
